# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'

require 'bundler'
Bundler.setup

require 'motion-layout'

Motion::Project::App.setup do |app|
  app.name = 'MotionLayoutTest'
end
